AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs18.x
      Timeout: 60  # Timeout limint in seconds
      Events:
        HttpGetEvent:
          Type: Api
          Properties:
            Path: /test
            Method: get